language: python
cache: pip
python:
  - "2.7"
install: "pip install -r requirements.txt"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE USER zuul;'
  - createdb keymaster -O zuul
  - psql keymaster zuul -f db_init.sql
  - cp config.spec.py config.py
  - mkdir logs
script: "python -m unittest discover -v"
