language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE USER zuul;'
  - createdb keymaster -O zuul
  - psql keymaster zuul -f db_init.sql
  - sed 's/\/var\/log\/keymaster/logs/' config.spec.py > config.py
  - mkdir logs
  - python -m unittest -h
script: "python -m unittest discover"
