language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt"
script: "python tests.py"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE USER zuul;'
  - psql -U zuul -c 'CREATE DATABASE keymaster;'
  - psql keymaster zuul -f db_init.sql
